// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payslip4All.Infrastructure.Persistence;

#nullable disable

namespace Payslip4All.Infrastructure.Migrations
{
    [DbContext(typeof(PayslipDbContext))]
    [Migration("20260403143917_AddPayFastCardIntegrationAuditParity")]
    partial class AddPayFastCardIntegrationAuditParity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Payslip4All.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SarsPayeNumber")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("UifNumber")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyGrossSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("UifReference")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployeeNumber", "CompanyId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.EmployeeLoan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthlyDeductionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfTerms")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("PaymentStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TermsCompleted")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<decimal>("TotalLoanAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "Status");

                    b.ToTable("EmployeeLoans");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.OutcomeNormalizationDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppliedPrecedence")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthoritativeOutcomeAfter")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthoritativeOutcomeBefore")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ConflictWithAcceptedFinalOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedOutcome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentReturnEvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SupersededAbandonment")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupersededNotConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TriggerSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UnmatchedPaymentReturnRecordId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WalletActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WalletEffect")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId");

                    b.ToTable("OutcomeNormalizationDecisions");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.PaymentReturnEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClaimedOutcome")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ConfirmedChargedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmedCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrelationDisposition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnvironmentMode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EvidenceOccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAtOrAfterAbandonmentThreshold")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MatchedAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantPaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethodCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSessionReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnCorrelationToken")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafePayloadSnapshot")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ServerConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SignatureVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceChannel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SourceVerified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrustLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidationMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatchedAttemptId");

                    b.ToTable("PaymentReturnEvidences");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Payslip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChargedAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GrossEarnings")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NetPay")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("PayPeriodMonth")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PayPeriodYear")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalDeductions")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalLoanDeductions")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UifDeduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("EmployeeId", "PayPeriodMonth", "PayPeriodYear")
                        .IsUnique()
                        .HasDatabaseName("UQ_Payslips_EmployeeId_PayPeriodMonth_PayPeriodYear");

                    b.ToTable("Payslips");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.PayslipLoanDeduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeLoanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PayslipId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeLoanId");

                    b.HasIndex("PayslipId");

                    b.ToTable("PayslipLoanDeductions");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.PayslipPricingSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerPayslip")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdatedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PayslipPricingSettings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            PricePerPayslip = 15.00m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.UnmatchedPaymentReturnRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationDisposition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayMessage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenericResultCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrimaryEvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafePayloadSnapshot")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UnmatchedPaymentReturnRecords");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentBalance")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m);

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.WalletActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ActivityType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BalanceAfterActivity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PaymentReturnEvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WalletId", "OccurredAt");

                    b.ToTable("WalletActivities");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.WalletTopUpAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AbandonAfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AbandonedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuthoritativeEvidenceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("AuthoritativeOutcomeAcceptedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ConfirmedChargedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreditedWalletActivityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FailureMessage")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("HostedPageDeadline")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastEvaluatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastEvidenceReceivedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastReconciledAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastValidatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantPaymentReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("NextReconciliationDueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeMessage")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutcomeReasonCode")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderPaymentReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSessionReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RedirectedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RequestedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnCorrelationToken")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MerchantPaymentReference");

                    b.HasIndex("ProviderSessionReference");

                    b.HasIndex("ReturnCorrelationToken");

                    b.HasIndex("UserId", "CreatedAt");

                    b.ToTable("WalletTopUpAttempts");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Company", b =>
                {
                    b.HasOne("Payslip4All.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Employee", b =>
                {
                    b.HasOne("Payslip4All.Domain.Entities.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.EmployeeLoan", b =>
                {
                    b.HasOne("Payslip4All.Domain.Entities.Employee", "Employee")
                        .WithMany("Loans")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Payslip", b =>
                {
                    b.HasOne("Payslip4All.Domain.Entities.Employee", "Employee")
                        .WithMany("Payslips")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.PayslipLoanDeduction", b =>
                {
                    b.HasOne("Payslip4All.Domain.Entities.EmployeeLoan", null)
                        .WithMany()
                        .HasForeignKey("EmployeeLoanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Payslip4All.Domain.Entities.Payslip", null)
                        .WithMany("LoanDeductions")
                        .HasForeignKey("PayslipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Payslip4All.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.WalletActivity", b =>
                {
                    b.HasOne("Payslip4All.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Activities")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.WalletTopUpAttempt", b =>
                {
                    b.HasOne("Payslip4All.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Company", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Payslips");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Payslip", b =>
                {
                    b.Navigation("LoanDeductions");
                });

            modelBuilder.Entity("Payslip4All.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
